name: RDPHijacker ~ @Zebratic

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Cleaning up from last workflow...
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Zebratic/RDPHijacker/main/Binaries/cleanup.bat -OutFile cleanup.bat
        start cleanup.bat
    - name: Installing ngrok and nssm...
      run: |
        Invoke-WebRequest https://github.com/Zebratic/RDPHijacker/blob/main/Binaries/ngrok.exe?raw=true -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/Zebratic/RDPHijacker/blob/main/Binaries/nssm.exe?raw=true -OutFile nssm.exe
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Linking your ngrok auth token...
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Preparing Hijack...
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Zebratic/RDPHijacker/main/Binaries/ngrok-setup.bat -OutFile ngrok-setup.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Zebratic/RDPHijacker/main/Binaries/ngrok-checkup.bat -OutFile ngrok-checkup.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Zebratic/RDPHijacker/main/Binaries/ngrok-monitor.bat -OutFile ngrok-monitor.bat
    - name: Hijacking...
      run:  start ngrok-setup.bat
    - name: Enabling RDP access...
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Opening ngrok tunnel...
      run: sc start ngrok
    - name: Now monitoring ngrok...
      run: cmd /c ngrok-checkup.bat
    - name: RDP Successfully hijacked, you can now connect to it!
      run: cmd /c ngrok-monitor.bat 